apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  artifacts:
    - image: registry.jakepeterson.dev/jpetersondev/ms-ticketing/client
      context: client
      kaniko:
        cache: {}
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: registry.jakepeterson.dev/jpetersondev/ms-ticketing/auth
      context: auth
      kaniko:
        buildArgs: 
          NPM_TOKEN: "{{.NPM_TOKEN}}"
        cache: {}
      sync:
        manual:
          - src: '**/src/*.ts'
            dest: .
    - image: registry.jakepeterson.dev/jpetersondev/ms-ticketing/tickets
      context: tickets
      kaniko:
        buildArgs: 
          NPM_TOKEN: "{{.NPM_TOKEN}}"
        cache: {}
      sync:
        manual:
          - src: '**/src/*.ts'
            dest: .
    - image: registry.jakepeterson.dev/jpetersondev/ms-ticketing/orders
      context: orders
      kaniko:
        buildArgs: 
          NPM_TOKEN: "{{.NPM_TOKEN}}"
        cache: {}
      sync:
        manual:
          - src: '**/src/*.ts'
            dest: .
    # - image: registry.jakepeterson.dev/jpetersondev/ms-ticketing/nats-test
    #   context: nats-test
    #   kaniko:
    #     buildArgs: 
    #       NPM_TOKEN: "{{.NPM_TOKEN}}"
    #     cache: {}
    #   sync:
    #     manual:
    #       - src: '**/src/*.ts'
    #         dest: .
  cluster:
    # create kubernetes secret called kaniko-secret with kaniko secret and add the  name of the Kubernetes secret for pulling base images and pushing the final image. If given, the secret needs to contain the Google Cloud service account secret key under the key kaniko-secret.
    pullSecretName: kaniko-secret
    # Note that the Kubernetes secret must not be of type kubernetes.io/dockerconfigjson which stores the config json under the key ".dockerconfigjson", but an opaque secret with the key "config.json"
    dockerConfig:
      secretName: docker-cfg
    namespace: default
