apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: auth
          image: registry.gitlab.com/jpeterson-dev/ms-ticketing/auth:latest
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt_secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: default
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000