apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-client-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: ms-client
          image: registry.jakepeterson.dev/jtp03a/ms-ticketing/client:latest
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
  namespace: default
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3001
      targetPort: 3000