apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-test-pub-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-test-pub
  template:
    metadata:
      labels:
        app: nats-test-pub
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: nats-publisher
          image: registry.jakepeterson.dev/jpetersondev/ms-ticketing/nats-test:latest
          command: ["npm", "run", "publish"]