apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-test-ls-depl
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nats-test-ls
  template:
    metadata:
      labels:
        app: nats-test-ls
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: nats-listener
          image: registry.jakepeterson.dev/jpetersondev/ms-ticketing/nats-test:latest
          command: ["npm", "run", "listen"]