apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo
    spec:
      volumes:
      - name: orders-mongo-storage
        persistentVolumeClaim:
          claimName: orders-mongo
      containers:
        - name: orders-mongo
          image: mongo
          volumeMounts:
          - name: orders-mongo-storage
            mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
  namespace: default
spec:
  selector:
    app: orders-mongo
  ports:
    - name: orders-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
---      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
